[workspace]

members = [
    "hello_rust" ,
    "dyn_hello" ,
    "variables" ,
    "owner" ,
    "structs" ,
    "communicator" ,
    "collections" , 
    "handle_error" ,
    "gtl",
    "adder",
    "greprs",
    "how_r_u_rust",
    "drop_test",
]